Config = {}
Config.Apps =  {
    {
        id = 1,
        name = "Instashot",
        description = "Company name",
        downloads = 8794562,
        icon = "Instashot",
        installed = true,
        rate = 5,
        image = "appDetails",
        disabled = false,
    },
    {
        id = 2,
        name = "ChatBolbol",
        description = "Company name",
        downloads = 78562358,
        icon = "whatsApp",
        path = "/whatsApp",
        installed = true,
        rate = 3,
        image = "appDetails",
        disabled = false,
    },
    {
        id = 3,
        name = "Faces",
        description = "Company name",
        downloads = 1452851,
        icon = "facebook",
        path = "/facebook",
        installed = false,
        rate = 4,
        image = "appDetails",
        disabled = false,
    },
    {
        id = 4,
        name = "TicTakTok",
        description = "Company name",
        downloads = 7236,
        icon = "tiktok",
        path = "/tiktok",
        installed = true,
        rate = 5,
        image = "appDetails",
        disabled = false,
    },
    {
        id = 5,
        name = "EX",
        description = "Company name",
        downloads = 6541,
        icon = "ex",
        path = "/ex",
        installed = false,
        rate = 2,
        image = "appDetails",
        disabled = false,
    },
    {
        id = 6,
        name = "Maps",
        description = "Company name",
        downloads = 234,
        icon = "maps",
        path = "/maps",
        installed = true,
        rate = 5,
        image = "appDetails",
        disabled = false,
    },
    {
        id = 7,
        name = "SnapOO",
        description = "Company name",
        downloads = 145541298,
        icon = "snapchat",
        path = "/snapchat",
        installed = true,
        rate = 4,
        image = "appDetails",
        disabled = false,
    },
    {
        id = 8,
        name = "Shopping",
        description = "Company name",
        downloads = 234,
        icon = "shopping",
        path = "/shopping",
        installed = true,
        rate = 3,
        image = "appDetails",
        disabled = false,
    },
}
