import { XTweets } from "../../../config/inventory";
import { faker } from "@faker-js/faker";

export const Xdb: XTweets[] = [
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            img: faker.image.people(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            img: faker.image.abstract(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            img: faker.image.nature(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            img: faker.image.food(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            img: faker.image.business(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
    {
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        userName: faker.internet.userName(),
        avatar: faker.image.avatar(),
        tweet: {
            id: faker.string.uuid(),
            text: faker.lorem.paragraph(),
            likes: faker.number.int(10),
            retweets: faker.number.int(10),
            comments: faker.number.int(10),
        },
        liked: false,
        retweeted: false,
    },
];
